### ISSUE TITLE
unsafe use of Protect in motivation vignette

### ISSUE THREAD

**Issue by romainfrancois** [eddelbuettel/tidycpp#2]
This code in the motivation vignette (https://github.com/eddelbuettel/tidycpp/blob/2f2d740129db944544715cb93a4c81152c52f9de/vignettes/motivation.Rmd#L108) leaves 

```cpp
SEXP ans =
    R::Protect(R::allocMatrixReal(nx, ny));
```

leaves `ans` unprotected for the remaining of the function as the destructor is called immediately.

**Comment by eddelbuettel** [comment]
Good catch, thanks.

**Comment by eddelbuettel** [comment]
Done in fa54e5408d6eaccbf65a0d3f3e86fc176a1a4587 for examples and 71f9472d0ff13caf97cdfc8654d22bf8a63f0319 for vignette.
